# -*- coding: utf-8 -*-
"""Object Detection Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/119u3J3bULbFoH5VudpUMockk1UiWJrHt
"""

!nvidia-smi

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="2T80wqCJ4jtcYzmH7wkF")
project = rf.workspace("happy-ndtke").project("urpc-nzxfa-mmqfo")
version = project.version(1)
dataset = version.download("yolov12")

!pip install ultralytics

import yaml, os

def create_data_yaml(dataset_path, path_to_data_yaml):

    labels_path = os.path.join(dataset_path, 'train', 'labels')
    label_files = [f for f in os.listdir(labels_path) if f.endswith('.txt')]


    all_ids = set()
    for label_file in label_files:
        with open(os.path.join(labels_path, label_file), 'r') as f:
            for line in f:
                if len(line.strip()) > 0:
                    class_id = int(line.strip().split()[0])
                    all_ids.add(class_id)

    # Create class names (0,1,2,...)
    classes = [f'class_{i}' for i in sorted(all_ids)]
    number_of_classes = len(classes)

    data = {
        'path': dataset_path,
        'train': 'train/images',
        'val': 'valid/images',
        'nc': number_of_classes,
        'names': classes
    }


    with open(path_to_data_yaml, 'w') as f:
        yaml.dump(data, f, sort_keys=False)
    print(f'Created {path_to_data_yaml}')


dataset_path = '/content/URPC-1'
path_to_data_yaml = '/content/URPC-1/data.yaml'

create_data_yaml(dataset_path, path_to_data_yaml)


!cat /content/URPC-1/data.yaml

!yolo detect train data=/content/URPC-1/data.yaml model=yolo12s.pt epochs=60 imgsz=640

!yolo detect predict model=runs/detect/train/weights/best.pt source=/content/URPC-1/valid/images save=True

import glob
from IPython.display import Image, display


prediction_path = '/content/runs/detect/predict/'

# Get the first 10 .jpg images and display them
for image_path in sorted(glob.glob(f'{prediction_path}*.jpg'))[:10]:
    display(Image(filename=image_path, height=400))
    print(f"Displayed: {image_path}\n")

!zip -r runs.zip /content/runs


from google.colab import files
files.download('runs.zip')